modLoader = "javafml" #mandatory
loaderVersion = "[43,)" #mandatory This is typically bumped every Minecraft version by Forge. See https://files.minecraftforge.net/ for a list of versions.
license = "MIT" # Review your options at https://choosealicense.com/.
issueTrackerURL="https://github.com/jshipley/HauntFurnace/issues" #optional
[[mods]] #mandatory
modId = "hauntfurnace" #mandatory
version = "0.3.3" #mandatory
displayName = "Haunt Furnace" #mandatory
displayURL="https://modrinth.com/mod/haunt-furnace" #optional (displayed in the mod UI)
logoFile = "hauntfurnace.png" #optional (needs to be in the root of your mod jar (root of your 'resources' folder))
#credits = "Thanks for this example mod goes to Java" #optional
authors = "jshipley" #optional
description = '''A furnace that haunts your items and transforms them into something new. Inspired by the Create mod.''' #mandatory (Supports multiline text)
[[dependencies.hauntfurnace]] #optional
modId = "forge" #mandatory
mandatory = true #mandatory
versionRange = "[43,)" #mandatory
ordering = "NONE" # The order that this dependency should load in relation to your mod, required to be either 'BEFORE' or 'AFTER' if the dependency is not mandatory
side = "BOTH" # Side this dependency is applied on - 'BOTH', 'CLIENT' or 'SERVER'
[[dependencies.hauntfurnace]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,1.20)"
ordering = "NONE"
side = "BOTH"
