modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = "https://github.com/jshipley/HauntFurnace/issues"
license = "MIT"

[[mods]]
modId = "hauntfurnace"
version = "${version}"
displayName = "Haunt Furnace"
authors = "jshipley"
description = '''
A furnace that haunts your items and transforms them into something new. Inspired by the Create mod.
'''
logoFile = "hauntfurnace.png"

[[dependencies.hauntfurnace]]
modId = "neoforge"
type = "required"
versionRange = "[21.5,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.hauntfurnace]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.5,)"
ordering = "NONE"
side = "BOTH"


