modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = "https://github.com/jshipley/HauntFurnace/issues"
license = "MIT"

[[mods]]
modId = "hauntfurnace"
version = "${version}"
displayName = "Haunt Furnace"
authors = "jship"
description = '''
A furnace that haunts your items and transforms them into something new. Inspired by the Create mod.
'''
logoFile = "assets/hauntfurnace/hauntfurnace.png"

[[dependencies.hauntfurnace]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.hauntfurnace]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.hauntfurnace]]
modId = "architectury"
mandatory = true
type = "required"
versionRange = "[13.0,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.hauntfurnace]]
modId = "yet_another_config_lib_v3"
mandatory = true
type = "required"
versionRange = "[3.6.6,)"
ordering = "NONE"
side = "CLIENT"

