package com.jship.hauntfurnace.datagen.fabric;

import net.fabricmc.fabric.api.datagen.v1.FabricDataOutput;
import net.fabricmc.fabric.api.datagen.v1.provider.FabricTagProvider;
import net.minecraft.core.HolderLookup;
import net.minecraft.core.registries.Registries;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.tags.TagKey;
import net.minecraft.world.item.Item;

import com.jship.hauntfurnace.HauntFurnace;
import net.minecraft.world.item.Items;

import java.util.concurrent.CompletableFuture;

public class ItemTagGenerator extends FabricTagProvider<Item> {
    public static final TagKey<Item> RED_WOODS = TagKey.create(Registries.ITEM, HauntFurnace.id("red_woods"));
    public static final TagKey<Item> RED_LEAVES = TagKey.create(Registries.ITEM, HauntFurnace.id("red_leaves"));
    public static final TagKey<Item> GREEN_WOODS = TagKey.create(Registries.ITEM, HauntFurnace.id("green_woods"));
    public static final TagKey<Item> GREEN_LEAVES = TagKey.create(Registries.ITEM, HauntFurnace.id("green_leaves"));
    
    public ItemTagGenerator(FabricDataOutput output, CompletableFuture<HolderLookup.Provider> registriesFuture) {
        super(output, Registries.ITEM, registriesFuture);
    }

    @Override
    protected void addTags(HolderLookup.Provider lookup) {
        getOrCreateTagBuilder(RED_WOODS)
                .add(Items.ACACIA_LOG).add(Items.STRIPPED_ACACIA_LOG).add(Items.ACACIA_WOOD).add(Items.STRIPPED_ACACIA_WOOD)
                .add(Items.CHERRY_LOG).add(Items.STRIPPED_CHERRY_LOG).add(Items.CHERRY_WOOD).add(Items.STRIPPED_CHERRY_WOOD)
                .add(Items.JUNGLE_LOG).add(Items.STRIPPED_JUNGLE_LOG).add(Items.JUNGLE_WOOD).add(Items.STRIPPED_JUNGLE_WOOD)
                .add(Items.MANGROVE_LOG).add(Items.STRIPPED_MANGROVE_LOG).add(Items.MANGROVE_WOOD).add(Items.STRIPPED_MANGROVE_WOOD)
                
                .addOptional(ResourceLocation.fromNamespaceAndPath("charm", "azalea_log"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("charm", "stripped_azalea_log"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("charm", "azalea_wood"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("charm", "stripped_azalea_wood"))
                
                .addOptional(ResourceLocation.fromNamespaceAndPath("quark", "azalea_log"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("quark", "stripped_azalea_log"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("quark", "azalea_wood"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("quark", "stripped_azalea_wood"))
                
                .addOptional(ResourceLocation.fromNamespaceAndPath("croptopia", "cinnamon_log"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("croptopia", "stripped_cinnamon_log"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("croptopia", "cinnamon_wood"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("croptopia", "stripped_cinnamon_wood"))
                
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomesoplenty", "fir_log"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomesoplenty", "stripped_fir_log"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomesoplenty", "fir_wood"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomesoplenty", "stripped_fir_wood"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomesoplenty", "maple_log"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomesoplenty", "stripped_maple_log"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomesoplenty", "maple_wood"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomesoplenty", "stripped_maple_wood"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomesoplenty", "redwood_log"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomesoplenty", "stripped_redwood_log"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomesoplenty", "redwood_wood"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomesoplenty", "stripped_redwood_wood"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomesoplenty", "mahogany_log"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomesoplenty", "stripped_mahogany_log"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomesoplenty", "mahogany_wood"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomesoplenty", "stripped_mahogany_wood"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomesoplenty", "palm_log"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomesoplenty", "stripped_palm_log"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomesoplenty", "palm_wood"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomesoplenty", "stripped_palm_wood"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomesoplenty", "hellbark_log"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomesoplenty", "stripped_hellbark_log"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomesoplenty", "hellbark_wood"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomesoplenty", "stripped_hellbark_wood"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomesoplenty", "empyrial_log"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomesoplenty", "stripped_empyrial_log"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomesoplenty", "empyrial_wood"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomesoplenty", "stripped_empyrial_wood"))

                .addOptional(ResourceLocation.fromNamespaceAndPath("biomeswevegone", "aspen_log"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomeswevegone", "stripped_aspen_log"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomeswevegone", "aspen_wood"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomeswevegone", "stripped_aspen_wood"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomeswevegone", "cika_log"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomeswevegone", "stripped_cika_log"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomeswevegone", "cika_wood"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomeswevegone", "stripped_cika_wood"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomeswevegone", "fir_log"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomeswevegone", "stripped_fir_log"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomeswevegone", "fir_wood"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomeswevegone", "stripped_fir_wood"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomeswevegone", "holly_log"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomeswevegone", "stripped_holly_log"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomeswevegone", "holly_wood"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomeswevegone", "stripped_holly_wood"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomeswevegone", "jacaranda_log"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomeswevegone", "stripped_jacaranda_log"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomeswevegone", "jacaranda_wood"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomeswevegone", "stripped_jacaranda_wood"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomeswevegone", "mahogany_log"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomeswevegone", "stripped_mahogany_log"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomeswevegone", "mahogany_wood"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomeswevegone", "stripped_mahogany_wood"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomeswevegone", "rainbow_eucalyptus_log"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomeswevegone", "stripped_rainbow_eucalyptus_log"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomeswevegone", "rainbow_eucalyptus_wood"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomeswevegone", "stripped_rainbow_eucalyptus_wood"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomeswevegone", "redwood_log"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomeswevegone", "stripped_redwood_log"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomeswevegone", "redwood_wood"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomeswevegone", "stripped_redwood_wood"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomeswevegone", "sakura_log"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomeswevegone", "stripped_sakura_log"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomeswevegone", "sakura_wood"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomeswevegone", "stripped_sakura_wood"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomeswevegone", "zelkova_log"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomeswevegone", "stripped_zelkova_log"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomeswevegone", "zelkova_wood"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomeswevegone", "stripped_zelkova_wood"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomeswevegone", "blue_enchanted_log"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomeswevegone", "stripped_blue_enchanted_log"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomeswevegone", "blue_enchanted_wood"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomeswevegone", "stripped_blue_enchanted_wood"))
                
                .addOptional(ResourceLocation.fromNamespaceAndPath("regionsunexplored", "alpha_log"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("regionsunexplored", "stripped_alpha_log"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("regionsunexplored", "alpha_wood"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("regionsunexplored", "stripped_alpha_wood"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("regionsunexplored", "ashen_log"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("regionsunexplored", "stripped_ashen_log"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("regionsunexplored", "ashen_wood"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("regionsunexplored", "stripped_ashen_wood"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("regionsunexplored", "baobob_log"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("regionsunexplored", "stripped_baobob_log"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("regionsunexplored", "baobob_wood"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("regionsunexplored", "stripped_baobob_wood"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("regionsunexplored", "eucalyptus_log"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("regionsunexplored", "stripped_eucalyptus_log"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("regionsunexplored", "eucalyptus_wood"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("regionsunexplored", "stripped_eucalyptus_wood"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("regionsunexplored", "kapok_log"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("regionsunexplored", "stripped_kapok_log"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("regionsunexplored", "kapok_wood"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("regionsunexplored", "stripped_kapok_wood"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("regionsunexplored", "magnolia_log"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("regionsunexplored", "stripped_magnolia_log"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("regionsunexplored", "magnolia_wood"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("regionsunexplored", "stripped_magnolia_wood"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("regionsunexplored", "pine_log"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("regionsunexplored", "stripped_pine_log"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("regionsunexplored", "pine_wood"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("regionsunexplored", "stripped_pine_wood"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("regionsunexplored", "redwood_log"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("regionsunexplored", "stripped_redwood_log"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("regionsunexplored", "redwood_wood"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("regionsunexplored", "stripped_redwood_wood"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("regionsunexplored", "socotra_log"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("regionsunexplored", "stripped_socotra_log"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("regionsunexplored", "socotra_wood"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("regionsunexplored", "stripped_socotra_wood"));
        
        getOrCreateTagBuilder(RED_LEAVES)
                .add(Items.ACACIA_LEAVES)
                .add(Items.CHERRY_LEAVES)
                .add(Items.JUNGLE_LEAVES)
                .add(Items.MANGROVE_LEAVES)

                .addOptional(ResourceLocation.fromNamespaceAndPath("biomesoplenty", "fir_leaves"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomesoplenty", "maple_leaves"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomesoplenty", "redwood_leaves"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomesoplenty", "mahogany_leaves"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomesoplenty", "palm_leaves"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomesoplenty", "hellbark_leaves"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomesoplenty", "empyrial_leaves"))

                .addOptional(ResourceLocation.fromNamespaceAndPath("biomeswevegone", "aspen_leaves"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomeswevegone", "cika_leaves"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomeswevegone", "fir_leaves"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomeswevegone", "holly_leaves"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomeswevegone", "jacaranda_leaves"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomeswevegone", "mahogany_leaves"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomeswevegone", "rainbow_eucalyptus_leaves"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomeswevegone", "redwood_leaves"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomeswevegone", "sakura_leaves"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomeswevegone", "zelkova_leaves"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomeswevegone", "blue_enchanted_leaves"))
                
                .addOptional(ResourceLocation.fromNamespaceAndPath("regionsunexplored", "alpha_leaves"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("regionsunexplored", "ashen_leaves"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("regionsunexplored", "baobob_leaves"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("regionsunexplored", "eucalyptus_leaves"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("regionsunexplored", "kapok_leaves"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("regionsunexplored", "magnolia_leaves"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("regionsunexplored", "pine_leaves"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("regionsunexplored", "redwood_leaves"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("regionsunexplored", "socotra_leaves"));
                
        getOrCreateTagBuilder(GREEN_WOODS)
                .add(Items.BIRCH_LOG).add(Items.STRIPPED_BIRCH_LOG).add(Items.BIRCH_WOOD).add(Items.STRIPPED_BIRCH_WOOD)
                .add(Items.DARK_OAK_LOG).add(Items.STRIPPED_DARK_OAK_LOG).add(Items.DARK_OAK_WOOD).add(Items.STRIPPED_DARK_OAK_WOOD)
                .add(Items.OAK_LOG).add(Items.STRIPPED_OAK_LOG).add(Items.OAK_WOOD).add(Items.STRIPPED_OAK_WOOD)
                .add(Items.SPRUCE_LOG).add(Items.STRIPPED_SPRUCE_LOG).add(Items.SPRUCE_WOOD).add(Items.STRIPPED_SPRUCE_WOOD)

                .addOptional(ResourceLocation.fromNamespaceAndPath("charm", "ebony_log"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("charm", "stripped_ebony_log"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("charm", "ebony_wood"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("charm", "stripped_ebony_wood"))

                .addOptional(ResourceLocation.fromNamespaceAndPath("quark", "ancient_log"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("quark", "stripped_ancient_log"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("quark", "ancient_wood"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("quark", "stripped_ancient_wood"))

                .addOptional(ResourceLocation.fromNamespaceAndPath("biomesoplenty", "pine_log"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomesoplenty", "stripped_pine_log"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomesoplenty", "pine_wood"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomesoplenty", "stripped_pine_wood"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomesoplenty", "jacaranda_log"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomesoplenty", "stripped_jacaranda_log"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomesoplenty", "jacaranda_wood"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomesoplenty", "stripped_jacaranda_wood"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomesoplenty", "willow_log"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomesoplenty", "stripped_willow_log"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomesoplenty", "willow_wood"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomesoplenty", "stripped_willow_wood"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomesoplenty", "dead_log"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomesoplenty", "stripped_dead_log"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomesoplenty", "dead_wood"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomesoplenty", "stripped_dead_wood"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomesoplenty", "magic_log"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomesoplenty", "stripped_magic_log"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomesoplenty", "magic_wood"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomesoplenty", "stripped_magic_wood"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomesoplenty", "umbran_log"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomesoplenty", "stripped_umbran_log"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomesoplenty", "umbran_wood"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomesoplenty", "stripped_umbran_wood"))

                .addOptional(ResourceLocation.fromNamespaceAndPath("biomeswevegone", "baobob_log"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomeswevegone", "stripped_baobob_log"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomeswevegone", "baobob_wood"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomeswevegone", "stripped_baobob_wood"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomeswevegone", "ebony_log"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomeswevegone", "stripped_ebony_log"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomeswevegone", "ebony_wood"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomeswevegone", "stripped_ebony_wood"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomeswevegone", "ironwood_log"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomeswevegone", "stripped_ironwood_log"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomeswevegone", "ironwood_wood"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomeswevegone", "stripped_ironwood_wood"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomeswevegone", "maple_log"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomeswevegone", "stripped_maple_log"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomeswevegone", "maple_wood"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomeswevegone", "stripped_maple_wood"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomeswevegone", "palm_log"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomeswevegone", "stripped_palm_log"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomeswevegone", "palm_wood"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomeswevegone", "stripped_palm_wood"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomeswevegone", "pine_log"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomeswevegone", "stripped_pine_log"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomeswevegone", "pine_wood"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomeswevegone", "stripped_pine_wood"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomeswevegone", "skyrus_log"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomeswevegone", "stripped_skyrus_log"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomeswevegone", "skyrus_wood"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomeswevegone", "stripped_skyrus_wood"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomeswevegone", "spirit_log"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomeswevegone", "stripped_spirit_log"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomeswevegone", "spirit_wood"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomeswevegone", "stripped_spirit_wood"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomeswevegone", "white_mangrove_log"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomeswevegone", "stripped_white_mangrove_log"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomeswevegone", "white_mangrove_wood"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomeswevegone", "stripped_white_mangrove_wood"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomeswevegone", "willow_log"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomeswevegone", "stripped_willow_log"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomeswevegone", "willow_wood"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomeswevegone", "stripped_willow_wood"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomeswevegone", "witchhazel_log"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomeswevegone", "stripped_witchhazel_log"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomeswevegone", "witchhazel_wood"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomeswevegone", "stripped_witchhazel_wood"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomeswevegone", "palo_verde_log"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomeswevegone", "stripped_palo_verde_log"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomeswevegone", "palo_verde_wood"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomeswevegone", "stripped_palo_verde_wood"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomeswevegone", "green_enchanted_log"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomeswevegone", "stripped_green_enchanted_log"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomeswevegone", "green_enchanted_wood"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomeswevegone", "stripped_green_enchanted_wood"))
                
                .addOptional(ResourceLocation.fromNamespaceAndPath("regionsunexplored", "blackwood_log"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("regionsunexplored", "stripped_blackwood_log"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("regionsunexplored", "blackwood_wood"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("regionsunexplored", "stripped_blackwood_wood"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("regionsunexplored", "cobalt_log"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("regionsunexplored", "stripped_cobalt_log"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("regionsunexplored", "cobalt_wood"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("regionsunexplored", "stripped_cobalt_wood"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("regionsunexplored", "cypress_log"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("regionsunexplored", "stripped_cypress_log"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("regionsunexplored", "cypress_wood"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("regionsunexplored", "stripped_cypress_wood"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("regionsunexplored", "joshua_log"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("regionsunexplored", "stripped_joshua_log"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("regionsunexplored", "joshua_wood"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("regionsunexplored", "stripped_joshua_wood"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("regionsunexplored", "larch_log"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("regionsunexplored", "stripped_larch_log"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("regionsunexplored", "larch_wood"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("regionsunexplored", "stripped_larch_wood"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("regionsunexplored", "maple_log"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("regionsunexplored", "stripped_maple_log"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("regionsunexplored", "maple_wood"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("regionsunexplored", "stripped_maple_wood"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("regionsunexplored", "mauve_log"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("regionsunexplored", "stripped_mauve_log"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("regionsunexplored", "mauve_wood"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("regionsunexplored", "stripped_mauve_wood"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("regionsunexplored", "palm_log"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("regionsunexplored", "stripped_palm_log"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("regionsunexplored", "palm_wood"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("regionsunexplored", "stripped_palm_wood"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("regionsunexplored", "silver_birch_log"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("regionsunexplored", "stripped_silver_birch_log"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("regionsunexplored", "silver_birch_wood"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("regionsunexplored", "stripped_silver_birch_wood"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("regionsunexplored", "willow_log"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("regionsunexplored", "stripped_willow_log"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("regionsunexplored", "willow_wood"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("regionsunexplored", "stripped_willow_wood"));
        
        getOrCreateTagBuilder(GREEN_LEAVES)
                .add(Items.BIRCH_LEAVES)
                .add(Items.DARK_OAK_LEAVES)
                .add(Items.OAK_LEAVES)
                .add(Items.SPRUCE_LEAVES)
                .addOptional(ResourceLocation.fromNamespaceAndPath("charm", "ebony_leaves"))

                .addOptional(ResourceLocation.fromNamespaceAndPath("quark", "ancient_leaves"))

                .addOptional(ResourceLocation.fromNamespaceAndPath("biomesoplenty", "pine_leaves"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomesoplenty", "jacaranda_leaves"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomesoplenty", "willow_leaves"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomesoplenty", "dead_leaves"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomesoplenty", "magic_leaves"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomesoplenty", "umbran_leaves"))

                .addOptional(ResourceLocation.fromNamespaceAndPath("biomeswevegone", "baobob_leaves"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomeswevegone", "ebony_leaves"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomeswevegone", "ironwood_leaves"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomeswevegone", "maple_leaves"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomeswevegone", "palm_leaves"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomeswevegone", "pine_leaves"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomeswevegone", "skyrus_leaves"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomeswevegone", "spirit_leaves"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomeswevegone", "white_mangrove_leaves"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomeswevegone", "willow_leaves"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomeswevegone", "witchhazel_leaves"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomeswevegone", "palo_verde_leaves"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("biomeswevegone", "green_enchanted_leaves"))
                
                .addOptional(ResourceLocation.fromNamespaceAndPath("regionsunexplored", "blackwood_leaves"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("regionsunexplored", "cobalt_leaves"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("regionsunexplored", "cypress_leaves"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("regionsunexplored", "joshua_leaves"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("regionsunexplored", "larch_leaves"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("regionsunexplored", "maple_leaves"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("regionsunexplored", "mauve_leaves"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("regionsunexplored", "palm_leaves"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("regionsunexplored", "silver_birch_leaves"))
                .addOptional(ResourceLocation.fromNamespaceAndPath("regionsunexplored", "willow_leaves"));
    }
}
